"""10d

Revision ID: 16c2c6d92523
Revises: None
Create Date: 2016-08-16 13:54:25.330000

"""

# revision identifiers, used by Alembic.
revision = '16c2c6d92523'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
