"""11f

Revision ID: 5329ceabcb6e
Revises: 97bdb08f9d6a
Create Date: 2016-08-17 09:55:06.313000

"""

# revision identifiers, used by Alembic.
revision = '5329ceabcb6e'
down_revision = '97bdb08f9d6a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
